### ISSUE TITLE
Error when db seed

### ISSUE THREAD

**Issue by janszczepanski** [redwoodjs/example-invoice#46]
After installing the dependencies and do "db up" the comment "db seed" returns the following error message:
_Argument id: Got invalid value 1 on prisma.findOneInvoice. Provided Int, expected String._

**Comment by dale-french** [comment]
Related to #35 

@thedavidprice i'm happy to pick these issues up and get them fixed.

**Comment by thedavidprice** [comment]
Thanks, all! This is effectively a duplicate Issue so closing in favor of https://github.com/redwoodjs/example-invoice/issues/35

@dale-french Could you ping Peter P again on #35? This is his project so I'm not sure about the status/need for seeding anymore. Thanks in advance!
